# Generated by Django 6.0.4 on 2026-05-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('nombre_garante', models.CharField(max_length=100)),
                ('ingresos_garante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modelo', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=50)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_adjudicacion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_retiro', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
