# Generated by Django 6.0.4 on 2026-06-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_nacimiento_garante',
            field=models.DateField(blank=True, null=True),
        ),
    ]
